## Array Summation

In [2]:
import numpy as np

In [3]:
x=np.array([[1,2,3],
[4,5,6],
[7,8,9]])




In [4]:
np.sum(x)

45

In [ ]:

np.sum(x,axis=None)
np.sum(x,axis=0)#summation of row

array([12, 15, 18])

In [10]:
np.sum(x,axis=1)#summation of colum

array([ 6, 15, 24])

In [12]:
np.sum(x,axis=1,keepdims=True)#summation of colum
#also keeping the dimensions

array([[ 6],
       [15],
       [24]])

## Array broadcasting 