np.dot(N,W)+b

In [ ]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

X, y = spiral_data(samples=100, classes=3)


In [2]:
nnfs.init()

In [3]:
X, y = spiral_data(samples=100, classes=3)

In [4]:
X.shape,y.shape

((300, 2), (300,))

In [5]:
class dense_layer:
    def __init__(self, inputs,neurons):
        self.weights= 0.01*np.random.randn(inputs,neurons)
        self.biases=np.zeros((1,neurons))
    def forward(self,inputs):
        self.output=np.dot(inputs,self.weights)+self.biases


In [6]:
dense1=dense_layer(2,3)

In [7]:
dense1.forward(X)

In [8]:
print("\nOutput of the first 5 samples:")
print(dense1.output[:5])


Output of the first 5 samples:
[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-1.0475188e-04  1.1395361e-04 -4.7983500e-05]
 [-2.7414842e-04  3.1729150e-04 -8.6921798e-05]
 [-4.2188365e-04  5.2666257e-04 -5.5912682e-05]
 [-5.7707680e-04  7.1401405e-04 -8.9430439e-05]]
