<div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 10px; text-align: center; font-family: 'Arial Black', sans-serif; font-size: 24px; text-shadow: 2px 2px 4px rgba(0,0,0,0.3); margin-bottom: 20px;">
🧠 SINGLE NEURON 🧠
</div>

In [1]:
import numpy as np

<div style="background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%); color: white; padding: 15px; border-radius: 8px; font-family: 'Courier New', monospace; font-size: 20px; font-weight: bold; text-align: center; text-shadow: 1px 1px 3px rgba(0,0,0,0.5); border: 3px solid #ff6b6b; box-shadow: 0 4px 8px rgba(0,0,0,0.2);">
🔢 VECTOR - VECTOR [NEURON] 🔢
</div>

<div style="background-color: #f8f9fa; padding: 10px; border-left: 5px solid #007bff; margin-top: 10px; font-family: 'Arial', sans-serif; color: #495057;">
<strong>Formula:</strong> <code style="background-color: #e9ecef; padding: 2px 6px; border-radius: 3px; color: #dc3545;">output = Σ(inputs × weights) + bias</code>
</div>

In [2]:
inputs = [1, 2, 3, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2

output_neuron= np.dot(inputs, weights) + bias
print(output_neuron)

4.8


<div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 15px; text-align: center; font-family: 'Arial Black', sans-serif; font-size: 28px; text-shadow: 2px 2px 4px rgba(0,0,0,0.3); margin-bottom: 20px; border: 4px solid #ffffff; box-shadow: 0 6px 12px rgba(0,0,0,0.2);">
🔢 VECTOR-MATRIX dot product aka --> [LAYERING] 🔢
</div>

<div style="background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%); color: white; padding: 15px; border-radius: 10px; font-family: 'Arial', sans-serif; font-size: 18px; font-weight: bold; text-shadow: 1px 1px 3px rgba(0,0,0,0.5); margin: 15px 0; border: 3px solid #ff6b6b;">
🧠 CORE CONCEPT
</div>

<div style="background-color: #f8f9fa; padding: 15px; border-radius: 8px; border-left: 5px solid #007bff; margin: 10px 0; font-family: 'Arial', sans-serif; color: #495057; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
When you compute <code style="background-color: #e9ecef; padding: 2px 6px; border-radius: 3px; color: #dc3545; font-weight: bold;">np.dot(weights, inputs)</code>, you're performing <strong style="color: #007bff;">multiple dot products</strong> - one with each row of the weights matrix. The result is a new vector where each element comes from dotting the input vector with one row of the weights matrix.
</div>

<div style="background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%); color: white; padding: 15px; border-radius: 10px; font-family: 'Arial', sans-serif; font-size: 18px; font-weight: bold; text-shadow: 1px 1px 3px rgba(0,0,0,0.5); margin: 15px 0; border: 3px solid #ffffff;">
📊 VISUAL ANALOGY
</div>

<div style="background-color: #f8f9fa; padding: 20px; border-radius: 10px; margin: 15px 0; border: 2px solid #28a745; box-shadow: 0 4px 8px rgba(0,0,0,0.1);">
<div style="text-align: center; margin-bottom: 15px;">
<span style="background-color: #007bff; color: white; padding: 8px 15px; border-radius: 20px; font-weight: bold; font-family: 'Arial', sans-serif;">📥 INPUTS</span>
</div>

<div style="background-color: #ffffff; padding: 15px; border-radius: 8px; margin: 10px 0; border: 2px solid #ffc107;">
<code style="color: #dc3545; font-size: 16px;">[Feature1: 1, Feature2: 2, Feature3: 3]</code>
</div>

<div style="text-align: center; margin: 15px 0;">
<span style="background-color: #28a745; color: white; padding: 8px 15px; border-radius: 20px; font-weight: bold; font-family: 'Arial', sans-serif;">⚖️ WEIGHTS MATRIX</span>
</div>

<pre style="background-color: #ffffff; padding: 15px; border-radius: 8px; border: 2px solid #6c757d; font-family: 'Courier New', monospace; color: #495057; overflow-x: auto;">
         Neuron1  Neuron2  Neuron3
Feature1 [ 4       5       6    ]
Feature2 [ 7       8       9    ]
Feature3 [ 10      11      12   ]
</pre>

<div style="text-align: center; margin: 15px 0;">
<span style="background-color: #dc3545; color: white; padding: 8px 15px; border-radius: 20px; font-weight: bold; font-family: 'Arial', sans-serif;">➕ ADD BIAS</span>
</div>

<div style="background-color: #ffffff; padding: 15px; border-radius: 8px; border: 2px solid #17a2b8;">
<code style="color: #17a2b8; font-size: 16px; font-weight: bold;">[2, 3, 4] ← Bias for each neuron</code>
</div>

<div style="text-align: center; margin: 15px 0;">
<span style="background-color: #6f42c1; color: white; padding: 8px 15px; border-radius: 20px; font-weight: bold; font-family: 'Arial', sans-serif;">🧮 FINAL RESULT</span>
</div>

<div style="background-color: #ffffff; padding: 15px; border-radius: 8px; border: 2px solid #e83e8c;">
<code style="color: #e83e8c; font-size: 16px; font-weight: bold;">[50, 57, 64] ← Neuron outputs</code>
</div>
</div>

<div style="background: linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%); color: #8b4513; padding: 15px; border-radius: 10px; font-family: 'Arial', sans-serif; font-size: 18px; font-weight: bold; text-shadow: 1px 1px 2px rgba(0,0,0,0.3); margin: 15px 0; border: 3px solid #daa520;">
⚙️ STEP-BY-STEP PROCESS
</div>

<div style="background-color: #f8f9fa; padding: 20px; border-radius: 10px; margin: 15px 0; border: 2px solid #6f42c1;">
<pre style="background-color: #ffffff; padding: 15px; border-radius: 8px; border: 1px solid #dee2e6; font-family: 'Courier New', monospace; color: #495057; margin: 10px 0;">
weights = [[4, 5, 6],
           [7, 8, 9], 
           [10, 11, 12]]

inputs = [1, 2, 3]
bias = [2, 3, 4]

# Under the hood:
# Row 1: [4,5,6]·[1,2,3] = 4+10+18 = 32 + bias[0]=2 = 34
# Row 2: [7,8,9]·[1,2,3] = 7+16+27 = 50 + bias[1]=3 = 53  
# Row 3: [10,11,12]·[1,2,3] = 10+22+36 = 68 + bias[2]=4 = 72

result = np.dot(weights, inputs) + bias  # [34, 53, 72]
</pre>
</div>

<div style="background: linear-gradient(135deg, #a8edea 0%, #fed6e3 100%); color: #2c3e50; padding: 15px; border-radius: 10px; font-family: 'Arial', sans-serif; font-size: 18px; font-weight: bold; text-shadow: 1px 1px 2px rgba(0,0,0,0.3); margin: 15px 0; border: 3px solid #3498db;">
🧠 NEURAL NETWORK CONNECTION
</div>

<div style="background-color: #f8f9fa; padding: 15px; border-radius: 8px; margin: 10px 0; border-left: 5px solid #28a745; font-family: 'Arial', sans-serif; color: #495057;">
<ul style="list-style-type: none; padding-left: 0;">
<li><strong style="color: #007bff;">Weights Matrix</strong> = Layer weights (each row = weights for one neuron)</li>
<li><strong style="color: #28a745;">Input Vector</strong> = Single data sample</li>
<li><strong style="color: #dc3545;">Bias Vector</strong> = Bias for each neuron</li>
<li><strong style="color: #e83e8c;">Output Vector</strong> = <code style="background-color: #f8d7da; padding: 2px 6px; border-radius: 3px;">np.dot(weights, inputs) + bias</code></li>
</ul>
</div>

<div style="background: linear-gradient(135deg, #ff9a9e 0%, #fecfef 100%); color: white; padding: 15px; border-radius: 10px; font-family: 'Arial', sans-serif; font-size: 18px; font-weight: bold; text-shadow: 1px 1px 3px rgba(0,0,0,0.5); margin: 15px 0; border: 3px solid #ff6b6b;">
⚠️ CRITICAL ORDER NOTE
</div>

<div style="background-color: #fff3cd; border: 2px solid #ffc107; padding: 15px; border-radius: 8px; margin: 10px 0; font-family: 'Arial', sans-serif; color: #856404;">
<div style="margin-bottom: 10px;">
<span style="background-color: #28a745; color: white; padding: 5px 10px; border-radius: 15px; font-weight: bold;">✅ CORRECT ORDER</span>
<code style="background-color: #d4edda; padding: 2px 6px; border-radius: 3px; color: #155724; margin-left: 10px;">np.dot(weights, inputs) + bias</code> → (3,3) × (3,) → (3,) + (3,) → (3,)
</div>

<div style="margin-bottom: 10px;">
<span style="background-color: #dc3545; color: white; padding: 5px 10px; border-radius: 15px; font-weight: bold;">❌ WRONG ORDER</span>
<code style="background-color: #f8d7da; padding: 2px 6px; border-radius: 3px; color: #721c24; margin-left: 10px;">np.dot(inputs, weights) + bias</code> → (3,) × (3,3) → Dimension mismatch
</div>

<div style="background-color: #007bff; color: white; padding: 10px; border-radius: 5px; text-align: center; font-weight: bold; margin-top: 10px;">
NEURAL NETWORKS: WEIGHTS COME FIRST, THEN INPUTS!
</div>
</div>

In [17]:
inputs=[2,4,5,4.2]
weights=[[0.2,0.8,-0.5,1.0],
[0.5,-0.91,0.26,-0.5],
[-0.26,-0.27,0.17,0.87],
[0.5,0.1,0.4,0.2]]
biases=[2,3,0.5,0.7]




print("inputs")
print(inputs)
print("--------------------------------")

print("weights")
print(weights)
print("--------------------------------")

print("biases")
print(biases)
print("--------------------------------")       
print("dot product of weights and inputs")
layer_outputs=np.dot(weights,inputs)+biases
print(layer_outputs)
print("--------------------------------")

print("dot product of inputs and weights")
layer_outputs2=np.dot(inputs,weights)+biases
print(layer_outputs2)
print("--------------------------------")

print("transpose of weights")
transpose_weights=np.transpose(weights)
print(transpose_weights)
print("--------------------------------")

print("dot product of transpose of weights and inputs")
layer_outputs3=np.dot(transpose_weights,inputs)+biases
print(layer_outputs3)
print("--------------------------------")












inputs
[2, 4, 5, 4.2]
--------------------------------
weights
[[0.2, 0.8, -0.5, 1.0], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87], [0.5, 0.1, 0.4, 0.2]]
--------------------------------
biases
[2, 3, 0.5, 0.7]
--------------------------------
dot product of weights and inputs
[ 7.3   -0.44   3.404  4.94 ]
--------------------------------
dot product of inputs and weights
[5.2  0.03 3.07 5.89]
--------------------------------
transpose of weights
[[ 0.2   0.5  -0.26  0.5 ]
 [ 0.8  -0.91 -0.27  0.1 ]
 [-0.5   0.26  0.17  0.4 ]
 [ 1.   -0.5   0.87  0.2 ]]
--------------------------------
dot product of transpose of weights and inputs
[5.2  0.03 3.07 5.89]
--------------------------------


<div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 15px; text-align: center; font-family: 'Arial Black', sans-serif; font-size: 28px; text-shadow: 2px 2px 4px rgba(0,0,0,0.3); margin-bottom: 20px; border: 4px solid #ffffff; box-shadow: 0 6px 12px rgba(0,0,0,0.2);">
🔢 MATRIX-MATRIX DOT PRODUCT MULTIPLICATION 🔢
</div>

<div style="background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%); color: white; padding: 15px; border-radius: 10px; font-family: 'Arial', sans-serif; font-size: 18px; font-weight: bold; text-shadow: 1px 1px 3px rgba(0,0,0,0.5); margin: 15px 0; border: 3px solid #ff6b6b;">
🧠 CORE CONCEPT
</div>

<div style="background-color: #f8f9fa; padding: 15px; border-radius: 8px; border-left: 5px solid #007bff; margin: 10px 0; font-family: 'Arial', sans-serif; color: #495057; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
Matrix-matrix multiplication extends vector-matrix operations by taking <strong style="color: #007bff;">each row</strong> from the first matrix and performing vector-matrix dot products with the entire second matrix.
</div>

<div style="background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%); color: white; padding: 15px; border-radius: 10px; font-family: 'Arial', sans-serif; font-size: 18px; font-weight: bold; text-shadow: 1px 1px 3px rgba(0,0,0,0.5); margin: 15px 0; border: 3px solid #ffffff;">
📊 CLASS EXAM ANALOGY
</div>

<div style="background-color: #f8f9fa; padding: 20px; border-radius: 10px; margin: 15px 0; border: 2px solid #28a745; box-shadow: 0 4px 8px rgba(0,0,0,0.1);">
<div style="display: flex; justify-content: space-around; margin-bottom: 15px;">
<div style="text-align: center;">
<span style="background-color: #007bff; color: white; padding: 6px 12px; border-radius: 15px; font-weight: bold; font-family: 'Arial', sans-serif; font-size: 14px;">📚 STUDENT HOURS</span>
</div>
<div style="text-align: center;">
<span style="background-color: #28a745; color: white; padding: 6px 12px; border-radius: 15px; font-weight: bold; font-family: 'Arial', sans-serif; font-size: 14px;">⚖️ EXAM WEIGHTS</span>
</div>
<div style="text-align: center;">
<span style="background-color: #dc3545; color: white; padding: 6px 12px; border-radius: 15px; font-weight: bold; font-family: 'Arial', sans-serif; font-size: 14px;">🏆 SCORES</span>
</div>
</div>

<pre style="background-color: #ffffff; padding: 12px; border-radius: 6px; border: 2px solid #007bff; font-family: 'Courier New', monospace; color: #495057; overflow-x: auto; margin: 8px 0; font-size: 14px;">
Student 1 [1,2,3]  →  Exam Matrix  →  [48,54,60]
Student 2 [2,1,1]                   [25,29,33]  
Student 3 [5,3,2]                   [61,71,81]
</pre>
</div>

<div style="background: linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%); color: #8b4513; padding: 15px; border-radius: 10px; font-family: 'Arial', sans-serif; font-size: 18px; font-weight: bold; text-shadow: 1px 1px 2px rgba(0,0,0,0.3); margin: 15px 0; border: 3px solid #daa520;">
⚙️ THE GOLDEN RULE
</div>

<div style="background-color: #fff3cd; border: 2px solid #ffc107; padding: 15px; border-radius: 8px; margin: 10px 0; font-family: 'Arial', sans-serif; color: #856404;">
<strong>Matrix Multiplication Rule:</strong> Columns in Matrix A must equal rows in Matrix B
</div>

<div style="background: linear-gradient(135deg, #a8edea 0%, #fed6e3 100%); color: #2c3e50; padding: 15px; border-radius: 10px; font-family: 'Arial', sans-serif; font-size: 18px; font-weight: bold; text-shadow: 1px 1px 2px rgba(0,0,0,0.3); margin: 15px 0; border: 3px solid #3498db;">
🧠 NEURAL NETWORK APPLICATION
</div>

<div style="background-color: #f8f9fa; padding: 15px; border-radius: 8px; margin: 10px 0; border-left: 5px solid #28a745; font-family: 'Arial', sans-serif; color: #495057;">
<div style="display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin-bottom: 15px;">
<div style="background-color: #d4edda; padding: 10px; border-radius: 6px; border: 2px solid #28a745;">
<strong style="color: #155724;">Input X:</strong> (batch_size, features)<br>
<strong style="color: #155724;">Weights W:</strong> (neurons, features)
</div>
<div style="background-color: #f8d7da; padding: 10px; border-radius: 6px; border: 2px solid #dc3545;">
<strong style="color: #721c24;">❌ Problem:</strong> <code>np.dot(X, W)</code> fails
</div>
</div>

<div style="background-color: #d1ecf1; padding: 10px; border-radius: 6px; border: 2px solid #17a2b8; margin: 10px 0;">
<strong style="color: #0c5460;">✅ Solution:</strong> <code style="background-color: #ffffff; padding: 2px 6px; border-radius: 3px; color: #17a2b8; font-weight: bold;">np.dot(X, W.T)</code> → (batch_size, neurons)
</div>
</div>

<div style="background-color: #007bff; color: white; padding: 15px; border-radius: 8px; text-align: center; font-weight: bold; font-family: 'Arial', sans-serif; margin: 15px 0; box-shadow: 0 4px 8px rgba(0,0,0,0.2);">
🚀 ONE OPERATION PROCESSES ENTIRE BATCHES ACROSS ALL NEURONS! 🚀
</div>

<div style="background: linear-gradient(135deg, #ff9a9e 0%, #fecfef 100%); color: white; padding: 15px; border-radius: 10px; font-family: 'Arial', sans-serif; font-size: 18px; font-weight: bold; text-shadow: 1px 1px 3px rgba(0,0,0,0.5); margin: 15px 0; border: 3px solid #ff6b6b;">
❓ KEY TAKEAWAY
</div>

<div style="background-color: #f8f9fa; padding: 15px; border-radius: 8px; border: 2px solid #17a2b8; font-family: 'Arial', sans-serif; color: #495057;">
The single line <code style="background-color: #e9ecef; padding: 2px 6px; border-radius: 3px; color: #dc3545; font-weight: bold;">outputs = np.dot(inputs, weights.T) + biases</code> is the heart of neural network forward passes - efficiently processing entire batches simultaneously! 🤖
</div>

In [18]:
inputs=[[1.2,3.4,5.6,7.8],
[1.2,3.4,5.6,7.8],
[1.2,3.4,5.6,7.8]]
weights=[[0.1,0.2,0.3,0.4],
[0.5,0.6,0.7,0.8],
[0.9,1.0,1.1,1.2],
[1.3,1.4,1.5,1.6]]
biases=[2,3,4,5]

print("inputs")
print(inputs)
print("--------------------------------")

print("weights")
print(weights)
print("--------------------------------")   

print("biases")
print(biases)
print("--------------------------------")



transpose_weights=np.transpose(weights)
print("transpose of weights")
print(transpose_weights)
print("--------------------------------")


outputs=np.dot(inputs,transpose_weights)+biases
print("outputs")
print(outputs)
print("--------------------------------")





inputs
[[1.2, 3.4, 5.6, 7.8], [1.2, 3.4, 5.6, 7.8], [1.2, 3.4, 5.6, 7.8]]
--------------------------------
weights
[[0.1, 0.2, 0.3, 0.4], [0.5, 0.6, 0.7, 0.8], [0.9, 1.0, 1.1, 1.2], [1.3, 1.4, 1.5, 1.6]]
--------------------------------
biases
[2, 3, 4, 5]
--------------------------------
transpose of weights
[[0.1 0.5 0.9 1.3]
 [0.2 0.6 1.  1.4]
 [0.3 0.7 1.1 1.5]
 [0.4 0.8 1.2 1.6]]
--------------------------------
outputs
[[ 7.6 15.8 24.  32.2]
 [ 7.6 15.8 24.  32.2]
 [ 7.6 15.8 24.  32.2]]
--------------------------------


# First image
![Lecture 2.1](notes/lecture_2.1.jpg)

# Second image
![Lecture 2.2](notes/lecture2.2.jpg)